name = "MCBench"
uuid = "3951c326-33a3-4e32-9c78-203120422c33"
authors = ["Salvatore La Cagnina", "Cornelius Grunwald"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
